services:
  - type: web
    name: tg-stream-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BASE_URL
        sync: false
      - key: LINK_TTL_SECONDS
        value: "12960000"
      - key: FIREBASE_DB_URL
        sync: false
